version: '3'
services:
  app:
    image: kpoier/share-web:latest
    container_name: share-web
    ports:
      - "8050:8050"
    volumes:
      - ./path/to/filesfolder:/app/files
    environment:
      - FLASK_DEBUG=0
    restart: unless-stopped